image:
  repository: trinodb/trino
  tag: ${TRINO_VERSION}

server:
  workers: 2
  config:
    query.max-memory: 4GB
    query.max-memory-per-node: 1GB

catalog:
  iceberg:
    connector.name: iceberg
    hive.metastore.uri: thrift://hive-metastore:9083
    hive.s3.endpoint: ${MINIO_ENDPOINT}
    hive.s3.aws-access-key: ${MINIO_ROOT_USER}
    hive.s3.aws-secret-key: ${MINIO_ROOT_PASSWORD}
    hive.s3.path-style-access: true 