image:
  repository: trinodb/trino
  tag: ${TRINO_VERSION}

server:
  workers: 2
  config:
    query.max-memory: 4GB
    query.max-memory-per-node: 1GB
    http-server.authentication.type: PASSWORD

catalog:
  iceberg:
    connector.name: iceberg
    iceberg.catalog.type: jdbc
    iceberg.catalog.warehouse-location: file:///var/lib/trino/data
    iceberg.file-format: PARQUET
    parquet.compression-codec: SNAPPY